# Generated by Django 5.0.1 on 2024-01-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('numero_cnib', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('numero_compteur', models.AutoField(primary_key=True, serialize=False)),
                ('modele_compteur', models.CharField(max_length=255)),
                ('mode_facturation', models.CharField(max_length=255)),
                ('numero_carte', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtatAbonnement',
            fields=[
                ('code_etat', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exploitation',
            fields=[
                ('numero_exploitation', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('code_tarif', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('prime_fixe', models.IntegerField()),
                ('redevance', models.IntegerField()),
                ('amperage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branchement',
            fields=[
                ('id', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('type_branchement', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('parcelle', models.CharField(max_length=100)),
                ('rang', models.CharField(max_length=100)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.exploitation')),
            ],
        ),
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('code_pdv', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.exploitation')),
            ],
        ),
        migrations.CreateModel(
            name='Guichet',
            fields=[
                ('numero_guichet', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pointDeVente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.pointdevente')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_abonnement', models.CharField(max_length=50)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_mise_en_service', models.DateField(blank=True, null=True)),
                ('date_resiliation', models.DateField(blank=True, null=True)),
                ('timbre', models.IntegerField()),
                ('liasse', models.IntegerField()),
                ('numero_police', models.CharField(max_length=255)),
                ('frais_police', models.IntegerField()),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.abonne')),
                ('branchement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.branchement')),
                ('compteur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashpower.compteur')),
                ('etat_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.etatabonnement')),
                ('guichet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.guichet')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.tarif')),
            ],
        ),
        migrations.CreateModel(
            name='TrancheTarif',
            fields=[
                ('id', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('debut', models.IntegerField()),
                ('fin', models.IntegerField()),
                ('cout_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tde_trch', models.IntegerField()),
                ('tsdaae_trch', models.IntegerField()),
                ('tva_trch', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('numero_ticket', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tqr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('energie_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tsdaae', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cout_energie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code_token', models.CharField(max_length=255)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.abonnement')),
                ('guichet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashpower.guichet')),
            ],
        ),
    ]
