# Generated by Django 5.0.1 on 2024-01-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashpower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='adresse_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='compteur',
            name='numero_compteur',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
